# Generated by Django 3.2.6 on 2021-08-05 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='product_id',
            new_name='product_name',
        ),
    ]
