# Generated by Django 3.2.6 on 2021-08-05 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_product_id_items_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='productColor',
        ),
        migrations.RemoveField(
            model_name='products',
            name='size',
        ),
        migrations.AddField(
            model_name='items',
            name='size',
            field=models.CharField(choices=[('Large', 'L'), ('Medium', 'M'), ('Small', 'S')], default='S', max_length=6),
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productColor', models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='red', max_length=6)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.products')),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='product_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productcolor'),
        ),
    ]
