# Generated by Django 3.2.6 on 2021-08-05 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210805_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='product_color',
        ),
    ]
