# Generated by Django 3.2.6 on 2021-08-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_items_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='productName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
