# Generated by Django 3.2.6 on 2021-08-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210805_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='size',
            field=models.CharField(choices=[('Large', 'L'), ('Medium', 'M'), ('Small', 'S')], default='S', max_length=6),
        ),
        migrations.AlterUniqueTogether(
            name='items',
            unique_together={('productColor', 'size')},
        ),
    ]
